import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Auth screens (Login / Forgot / Register) ── MD3 Forest-Green palette
        'on-secondary-fixed': '#131f00',
        'inverse-primary': '#95d3ba',
        'on-primary-container': '#80bea6',
        'on-secondary-container': '#4b6d00',
        'tertiary-container': '#004f34',
        'surface-bright': '#f9f9ff',
        'on-primary': '#ffffff',
        'on-surface-variant': '#404944',
        tertiary: '#003623',
        'surface-container-highest': '#dce2f7',
        surface: '#f9f9ff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-surface': '#141b2b',
        'surface-dim': '#d3daef',
        'inverse-surface': '#293040',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f9f9ff',
        'surface-container-low': '#f1f3ff',
        'surface-container-high': '#e1e8fd',
        'surface-container-lowest': '#ffffff',
        primary: '#003527',
        'secondary-fixed-dim': '#a4d64c',
        'on-error': '#ffffff',
        'secondary-fixed': '#bff365',
        'surface-tint': '#2b6954',
        'on-tertiary-fixed': '#002113',
        'on-primary-fixed-variant': '#0b513d',
        secondary: '#476800',
        outline: '#707974',
        'primary-fixed-dim': '#95d3ba',
        'surface-variant': '#dce2f7',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#edf0ff',
        error: '#ba1a1a',
        'secondary-container': '#bcf063',
        'on-background': '#141b2b',
        'tertiary-fixed-dim': '#4edea3',
        'primary-container': '#064e3b',
        'tertiary-fixed': '#6ffbbe',
        'primary-fixed': '#b0f0d6',
        'surface-container': '#e9edff',
        'on-tertiary-container': '#31c98f',
        'on-secondary-fixed-variant': '#354e00',
        'error-container': '#ffdad6',
        'outline-variant': '#bfc9c3',
        'on-primary-fixed': '#002117',

        // ── App screens (Dashboard / Tanah / Air / Notif / Settings) ── MD3 Earthy-Green
        'app-primary': '#0d631b',
        'app-primary-container': '#2e7d32',
        'app-primary-fixed': '#a3f69c',
        'app-primary-fixed-dim': '#88d982',
        'app-on-primary-container': '#cbffc2',
        'app-on-primary-fixed': '#002204',
        'app-on-primary-fixed-variant': '#005312',
        'app-secondary': '#79564b',
        'app-secondary-container': '#fed0c1',
        'app-secondary-fixed': '#ffdbcf',
        'app-secondary-fixed-dim': '#e9bdae',
        'app-on-secondary-fixed': '#2d150d',
        'app-on-secondary-fixed-variant': '#5e3f35',
        'app-on-secondary-container': '#79574c',
        'app-tertiary': '#884200',
        'app-tertiary-container': '#ad5600',
        'app-tertiary-fixed': '#ffdcc6',
        'app-tertiary-fixed-dim': '#ffb786',
        'app-on-tertiary-fixed': '#311300',
        'app-on-tertiary-fixed-variant': '#723600',
        'app-on-tertiary-container': '#ffeee6',
        'app-surface': '#f9f9f9',
        'app-surface-container': '#eeeeee',
        'app-surface-container-low': '#f3f3f4',
        'app-surface-container-high': '#e8e8e8',
        'app-surface-container-highest': '#e2e2e2',
        'app-surface-container-lowest': '#ffffff',
        'app-surface-dim': '#dadada',
        'app-surface-bright': '#f9f9f9',
        'app-surface-variant': '#e2e2e2',
        'app-inverse-surface': '#2f3131',
        'app-inverse-on-surface': '#f0f1f1',
        'app-inverse-primary': '#88d982',
        'app-surface-tint': '#1b6d24',
        'app-on-surface': '#1a1c1c',
        'app-on-surface-variant': '#40493d',
        'app-on-background': '#1a1c1c',
        'app-background': '#f9f9f9',
        'app-outline': '#707a6c',
        'app-outline-variant': '#bfcaba',
        'app-error': '#ba1a1a',
        'app-error-container': '#ffdad6',
        'app-on-error': '#ffffff',
        'app-on-error-container': '#93000a',
        'app-on-primary': '#ffffff',
        'app-on-secondary': '#ffffff',
        'app-on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-margin': '24px',
        unit: '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'touch-target-min': '56px',
        'stack-sm': '8px',
        'card-padding': '20px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.01em',
            fontWeight: '700',
          },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-xl': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        'soft-elevation': '0 4px 20px rgba(121, 86, 75, 0.08)',
        'soft-elevation-lg': '0 4px 20px rgba(121, 86, 75, 0.12)',
        'top-nav': '0 -4px 20px rgba(121, 86, 75, 0.12)',
        'bottom-nav': '0 4px 20px rgba(121, 86, 75, 0.12)',
        'card-shadow': '0 4px 20px 0 rgba(121, 86, 75, 0.08)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'gauge-fill': {
          '0%': { transform: 'rotate(-135deg)' },
          '100%': { transform: 'rotate(calc(-135deg + var(--gauge-angle)))' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'chart-draw': {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'chart-draw': 'chart-draw 1.5s ease-out forwards',
      },
    },
  },
  plugins: [],
};

export default config;
