services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: kebun-melon-mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./docker/mosquitto/config/acl.conf:/mosquitto/config/acl.conf:ro
      - ./docker/mosquitto/config/pwfile:/mosquitto/config/pwfile:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    environment:
      MQTT_GATEWAY_USERNAME: ${MQTT_GATEWAY_USERNAME:-gateway_user}
      MQTT_GATEWAY_PASSWORD: ${MQTT_GATEWAY_PASSWORD}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mosquitto_pub -t ''agriculture/healthcheck'' -m ''ping'' -i healthcheck -u "$$MQTT_GATEWAY_USERNAME" -P "$$MQTT_GATEWAY_PASSWORD" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mosquitto-data:
  mosquitto-log:
